apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: registro-atividades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-content
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: frontend-content
          configMap:
            name: frontend-content
